site_name: AnkleExo documentation webpage
site_url: https://www.oscartesniere.com/

nav:
  - Home: index.md
  - Electrical:
      - CURRENT TEST ASSEMBLY (while Im away) : electrical/current_test_assembly.md
      - Overview: electrical/index.md
      - PCB: electrical/pcb.md
      - Wiring: electrical/wiring.md
      - CAN Testing : electrical/CANtesting.md
      - Power: electrical/power.md
      - Encoder debug : electrical/encoder_debug.md
      - Encoder wiring : electrical/encoder_wiring.md
  - Software:
      - Overview: software/index.md
      - C++ coding guidelines: software/cppguidelines.md
      - Motor control system: software/MotorControl.md
      - CAN Motor Interfaces: software/CANMotor.md
      - CAN Motor API : software/CAN Motor API.md
      - API: software/api.md
      - Encoder testing: software/encoder.md
      - Sensors Plotting: software/plotting.md
      - Serial Communication Protocol: software/Serial communication.md
      - Python Bluetooth API : software/Python-API.md
  - Mechanical:
      - Overview: mechanical/index.md
      - Parts: mechanical/parts.md
      - Assembly: mechanical/assembly.md

theme:
  name: readthedocs
#logo: assets/logo.png
# add a logo here !

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# to upload to the server : `rsync -avz ankledocs root@192.168.0.88:/root/ankledocs/ankledocs/`