; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
monitor_speed = 115200

; ================ UNIFIED CAN MOTOR  CODE (MIT) =================

[env:MIT_CAN_teensy41]
platform = teensy
board = teensy41
framework = arduino
build_src_filter =
    -<*>
    +<CAN_unified.cpp>
build_flags =
    -D PLATFORM_TEENSY41
    -D MIT_MODE
lib_deps =
    https://github.com/tonton81/FlexCAN_T4.git
targets = upload, monitor
[env:MIT_CAN_uno_r4]
platform = renesas-ra
board = uno_r4_wifi
framework = arduino
build_src_filter =
    -<*>
    +<CAN_unified.cpp>
build_flags =
    -D MIT_MODE
    -D PLATFORM_RENESAS_RA
targets = upload , monitor

; ================ UNIFIED CAN MOTOR  CODE (Servo) =================

[env:Servo_CAN_teensy41]
platform = teensy
board = teensy41
framework = arduino
build_src_filter =
    -<*>
    +<CAN_unified.cpp>
build_flags =
    -D PLATFORM_TEENSY41
    -D SERVO_MODE
lib_deps =
    https://github.com/tonton81/FlexCAN_T4.git
;targets = upload, monitor
[env:Servo_CAN_uno_r4]
platform = renesas-ra
board = uno_r4_wifi
framework = arduino
build_src_filter =
    -<*>
    +<CAN_unified.cpp>
build_flags =
    -D SERVO_MODE
    -D PLATFORM_RENESAS_RA
targets = upload , monitor
; ================UNIFIED  LOAD CELL CODE =================

[env:LC_teensy41]
platform = teensy
board = teensy41
framework = arduino
build_src_filter =
    -<*>
    +<LoadCell_unified.cpp>
build_flags =
    -D PLATFORM_TEENSY41
targets = upload, monitor

[env:LC_uno_r4]
platform = renesas-ra
board = uno_r4_wifi
framework = arduino
build_src_filter =
    -<*>
    +<LoadCell_unified.cpp>
build_flags =
    -D PLATFORM_RENESAS_RA
targets = upload, monitor

[env:LC_uno_r3]
platform = atmelavr
board = uno
framework = arduino
build_src_filter =
    -<*>
    +<LoadCell_unified.cpp>
build_flags =
    -D PLATFORM_ATMEL_AVR
targets = upload, monitor

; ============== UNIFIED ENCODER CODE  ======================

[env:encoders_teensy41]
platform = teensy
board = teensy41
framework = arduino
build_src_filter =
    -<*>
    +<LoadCell_unified.cpp>
build_flags =
    -D PLATFORM_TEENSY41
targets = upload, monitor

[env:encoders_uno_r4]
platform = renesas-ra
board = uno_r4_wifi
framework = arduino
build_src_filter =
    -<*>
    +<Encoders_unified.cpp>
build_flags =
    -D PLATFORM_RENESAS_RA
targets = upload, monitor

[env:encoders_uno_r3]
platform = atmelavr
board = uno
framework = arduino
build_src_filter =
    -<*>
    +<Encoders_unified.cpp>
build_flags =
    -D PLATFORM_ATMEL_AVR
targets = upload, monitor



;------ justr a test for MIT mode

[env:MIT_DEBUG_R4]
platform = renesas-ra
board = uno_r4_wifi
framework = arduino
build_src_filter =
    -<*>
    +<cubemars_com_arduino_mit.cpp>
build_flags =
    -D PLATFORM_RENESAS_RA
targets = upload, monitor

[env:SERVO_DEBUG_R4]
platform = renesas-ra
board = uno_r4_wifi
framework = arduino
build_src_filter =
    -<*>
    +<main.cpp>
build_flags =
    -D PLATFORM_RENESAS_RA
targets = upload, monitor

; ============= SPI TESTS ===============

[env:spi_nano_master]
;build environment forload cell reading script. Works only on the Arduino R4
platform = nordicnrf52
board = nano33ble
framework = arduino
monitor_speed = 115200
build_src_filter =
    -<*>
    +<../test/spi_test/**>
    -<../test/spi_test/arduino_slave.cpp>
targets = upload, monitor

[env:spi_uno_slave]
;build environment forload cell reading script. Works only on the Arduino R4
platform = atmelavr
board = uno
framework=arduino
monitor_speed = 115200
build_src_filter =
    -<*>
    +<../test/spi_test/**>
    -<../test/spi_test/arduino_master.cpp>
targets = upload, monitor

;========

[env:SoftSPI]
platform =renesas-ra
board = uno_r4_wifi
framework = arduino
build_src_filter =
    -<*>
    +<../test/SoftSPITestScript.cpp>
lib_deps =
    robtillaart/SWSPI@^0.1.3
targets = upload, monitor