; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


; ================ UNIFIED CAN MOTOR  CODE =================
[env]
monitor_speed = 115200

[env:CAN_teensy41]
platform = teensy
board = teensy41
framework = arduino
build_src_filter =
    -<*>
    +<CAN_unified.cpp>
build_flags =
    -D PLATFORM_TEENSY41
lib_deps =
    https://github.com/tonton81/FlexCAN_T4.git
targets = upload, monitor
[env:CAN_uno_r4]
platform = renesas-ra
board = uno_r4_wifi
framework = arduino
build_src_filter =
    -<*>
    +<CAN_unified.cpp>
build_flags =
    -D PLATFORM_RENESAS_RA
targets = upload, monitor
; ================UNIFIED  LOAD CELL CODE =================

[env:LC_teensy41]
platform = teensy
board = teensy41
framework = arduino
build_src_filter =
    -<*>
    +<LoadCell_unified.cpp>
build_flags =
    -D PLATFORM_TEENSY41
targets = upload, monitor

[env:LC_uno_r4]
platform = renesas-ra
board = uno_r4_wifi
framework = arduino
build_src_filter =
    -<*>
    +<LoadCell_unified.cpp>
build_flags =
    -D PLATFORM_RENESAS_RA
targets = upload, monitor

[env:LC_uno_r3]
platform = atmelavr
board = uno
framework = arduino
build_src_filter =
    -<*>
    +<LoadCell_unified.cpp>
build_flags =
    -D PLATFORM_ATMEL_AVR
targets = upload, monitor

; ============== UNIFIED ENCODER CODE  ======================

[env:encoders_teensy41]
platform = teensy
board = teensy41
framework = arduino
build_src_filter =
    -<*>
    +<LoadCell_unified.cpp>
build_flags =
    -D PLATFORM_TEENSY41
targets = upload, monitor

[env:encoders_uno_r4]
platform = renesas-ra
board = uno_r4_wifi
framework = arduino
build_src_filter =
    -<*>
    +<Encoders_unified.cpp>
build_flags =
    -D PLATFORM_RENESAS_RA
targets = upload, monitor

[env:encoders_uno_r3]
platform = atmelavr
board = uno
framework = arduino
build_src_filter =
    -<*>
    +<Encoders_unified.cpp>
build_flags =
    -D PLATFORM_ATMEL_AVR
targets = upload, monitor

;------ justr a test for MIT mode

[env:MIT_DEBUG_R4]
platform = renesas-ra
board = uno_r4_wifi
framework = arduino
build_src_filter =
    -<*>
    +<cubemars_com_arduino_mit.cpp>
build_flags =
    -D PLATFORM_RENESAS_RA
targets = upload, monitor

[env:SERVO_DEBUG_R4]
platform = renesas-ra
board = uno_r4_wifi
framework = arduino
build_src_filter =
    -<*>
    +<main.cpp>
build_flags =
    -D PLATFORM_RENESAS_RA
targets = upload, monitor